import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import image1 from "../assets/images/image-1.jpg";
import image2 from "../assets/images/image-2.jpg";
import image3 from "../assets/images/image-3.jpg";
import image4 from "../assets/images/image-4.jpg";
const About = () => {
    return (_jsxs("section", { className: "relative container mx-auto px-14 mb-44", children: [_jsxs("div", { className: "flex justify-between items-center mb-24 relative z-10", children: [_jsx("h1", { className: "text-7xl font-black tracking-tighter leading-none", children: "ABOUT US" }), _jsxs("a", { href: "#", className: "text-sm uppercase flex items-center hover:opacity-70 transition-opacity", children: ["DISCOVER MORE", _jsx("span", { className: "ml-2", children: "\u2192" })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-20 relative z-10", children: [_jsxs("div", { className: "relative h-[600px]", children: [_jsx("div", { className: "absolute left-0 top-30 z-10", children: _jsx("img", { src: image3, alt: "Model in black turtleneck", className: "w-[360px] h-[500px] object-cover grayscale" }) }), _jsx("div", { className: "absolute right-10 top-0", children: _jsx("img", { src: image4, alt: "Model sitting", className: "w-[360px] h-[500px] object-cover grayscale" }) })] }), _jsxs("div", { className: "relative pt-12", children: [_jsx("p", { className: "text-sm uppercase leading-tight max-w-[300px] mb-8 font-semibold text-gray-700", children: "GAUCHERE COMBINES EXPERT CRAFTSMANSHIP WITH A COMMITMENT TO SUSTAINABILITY AND MODERN DESIGN." }), _jsx("span", { className: "absolute right-0 top-0 text-[200px] font-bold text-gray-100 select-none", children: "38" })] })] }), _jsx("div", { className: "mt-8 relative z-10", children: _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-20", children: [_jsx("div", { className: "relative", children: _jsx("p", { className: "text-sm font-semibold uppercase leading-tight max-w-[300px] text-gray-700", children: "GAUCHERE IS A FRENCH PR\u00CAT-\u00C0-PORTER HOUSE FOUNDED IN PARIS BY DESIGNER MARIE-CHRISTINE STATZ" }) }), _jsxs("div", { className: "relative h-[600px] -mt-36", children: [_jsx("div", { className: "absolute right-0 top-0", children: _jsx("img", { src: image1, alt: "Model posing", className: "w-[360px] h-[500px] object-cover grayscale" }) }), _jsx("div", { className: "absolute -bottom-20 left-20", children: _jsx("img", { src: image2, alt: "Fashion detail", className: "w-[360px] h-[500px] object-cover grayscale" }) })] })] }) }), _jsx("div", { className: "absolute inset-0 flex items-end justify-center pointer-events-none z-0 overflow-hidden ", children: _jsx("h2", { className: "text-[240px] font-black tracking-tighter text-gray-200 whitespace-nowrap select-none ", children: "AUTHENTIC" }) })] }));
};
export default About;
